__all__ = ("CHARACTER_RARITY_MAP", "PERCENT_STAT_TYPES")


from .enums.gi import FightPropType

PERCENT_STAT_TYPES = (
    "FIGHT_PROP_HP_PERCENT",
    "FIGHT_PROP_ATTACK_PERCENT",
    "FIGHT_PROP_DEFENSE_PERCENT",
    "FIGHT_PROP_CRITICAL",
    "FIGHT_PROP_CRITICAL_HURT",
    "FIGHT_PROP_CHARGE_EFFICIENCY",
    "FIGHT_PROP_HEAL_ADD",
    "FIGHT_PROP_PHYSICAL_ADD_HURT",
    "FIGHT_PROP_FIRE_ADD_HURT",
    "FIGHT_PROP_ELEC_ADD_HURT",
    "FIGHT_PROP_WATER_ADD_HURT",
    "FIGHT_PROP_WIND_ADD_HURT",
    "FIGHT_PROP_ROCK_ADD_HURT",
    "FIGHT_PROP_ICE_ADD_HURT",
    "FIGHT_PROP_GRASS_ADD_HURT",
)

CHARACTER_RARITY_MAP: dict[str, int] = {
    "QUALITY_ORANGE": 5,
    "QUALITY_PURPLE": 4,
}

ASCENSION_TO_MAX_LEVEL: dict[int, int] = {
    0: 20,
    1: 40,
    2: 50,
    3: 60,
    4: 70,
    5: 80,
    6: 90,
}

DMG_BONUS_FIGHT_PROPS = (
    FightPropType.FIGHT_PROP_PHYSICAL_ADD_HURT,
    FightPropType.FIGHT_PROP_FIRE_ADD_HURT,
    FightPropType.FIGHT_PROP_ELEC_ADD_HURT,
    FightPropType.FIGHT_PROP_WATER_ADD_HURT,
    FightPropType.FIGHT_PROP_WIND_ADD_HURT,
    FightPropType.FIGHT_PROP_ROCK_ADD_HURT,
    FightPropType.FIGHT_PROP_ICE_ADD_HURT,
    FightPropType.FIGHT_PROP_GRASS_ADD_HURT,
)
