from enum import IntEnum, StrEnum

__all__ = (
    "Language",
    "EquipmentType",
    "ItemType",
    "StatType",
    "FightProp",
)


class Language(StrEnum):
    ENGLISH = "en"
    RUSSIAN = "ru"
    VIETNAMESE = "vi"
    THAI = "th"
    PORTUGUESE = "pt"
    KOREAN = "ko"
    JAPANESE = "ja"
    INDONESIAN = "id"
    FRENCH = "fr"
    SPANISH = "es"
    GERMAN = "de"
    TRADITIONAL_CHINESE = "zh-TW"
    SIMPLIFIED_CHINESE = "zh-CN"
    ITALIAN = "it"
    TURKISH = "tr"


class EquipmentType(StrEnum):
    FLOWER = "EQUIP_BRACER"
    FEATHER = "EQUIP_NECKLACE"
    SANDS = "EQUIP_SHOES"
    GOBLET = "EQUIP_RING"
    CIRCLET = "EQUIP_DRESS"


class ItemType(StrEnum):
    WEAPON = "ITEM_WEAPON"
    ARTIFACT = "ITEM_RELIQUARY"


class StatType(StrEnum):
    BASE_ATK = "FIGHT_PROP_BASE_ATTACK"
    FLAT_HP = "FIGHT_PROP_HP"
    FLAT_ATK = "FIGHT_PROP_ATTACK"
    FLAT_DEF = "FIGHT_PROP_DEFENSE"
    HP_PERCENT = "FIGHT_PROP_HP_PERCENT"
    ATK_PERCENT = "FIGHT_PROP_ATTACK_PERCENT"
    DEF_PERCENT = "FIGHT_PROP_DEFENSE_PERCENT"
    CRIT_RATE = "FIGHT_PROP_CRITICAL"
    CRIT_DMG = "FIGHT_PROP_CRITICAL_HURT"
    ENERGY_RECHARGE = "FIGHT_PROP_CHARGE_EFFICIENCY"
    HEALING_BONUS = "FIGHT_PROP_HEAL_ADD"
    ELEMENTAL_MASTERY = "FIGHT_PROP_ELEMENT_MASTERY"
    PHYSICAL_DMG_BONUS = "FIGHT_PROP_PHYSICAL_ADD_HURT"
    PYRO_DMG_BONUS = "FIGHT_PROP_FIRE_ADD_HURT"
    ELECTRO_DMG_BONUS = "FIGHT_PROP_ELEC_ADD_HURT"
    HYDRO_DMG_BONUS = "FIGHT_PROP_WATER_ADD_HURT"
    ANEMO_DMG_BONUS = "FIGHT_PROP_WIND_ADD_HURT"
    CRYO_DMG_BONUS = "FIGHT_PROP_ICE_ADD_HURT"
    GEO_DMG_BONUS = "FIGHT_PROP_ROCK_ADD_HURT"
    DENDRO_DMG_BONUS = "FIGHT_PROP_GRASS_ADD_HURT"


class FightProp(IntEnum):
    BASE_HP = 1
    HP = 2
    HP_PERCENT = 3
    BASE_ATK = 4
    ATK = 5
    ATK_PERCENT = 6
    BASE_DEF = 7
    DEF = 8
    DEF_PERCENT = 9
    BASE_SPD = 10
    SPD_PERCENT = 11
    CRIT_RATE = 20
    CRIT_DMG = 22
    ENERGY_RECHARGE = 23
    HEALING_BONUS = 26
    INCOMING_HEALING_BONUS = 27
    ELEMENTAL_MASTERY = 28

    # elemental damage bonus
    PHYSICAL_DMG_BONUS = 30
    PYRO_DMG_BONUS = 40
    ELECTRO_DMG_BONUS = 41
    HYDRO_DMG_BONUS = 42
    DENDRO_DMG_BONUS = 43
    ANEMO_DMG_BONUS = 44
    GEO_DMG_BONUS = 45
    CRYO_DMG_BONUS = 46

    # resistance
    PHYSICAL_RES = 29
    PYRO_RES = 50
    ELECTRO_RES = 51
    HYDRO_RES = 52
    DENDRO_RES = 53
    ANEMO_RES = 54
    GEO_RES = 55
    CRYO_RES = 56

    # energy cost
    PYRO_ENERGY_COST = 70
    ELECTRO_ENERGY_COST = 71
    HYDRO_ENERGY_COST = 72
    DENDRO_ENERGY_COST = 73
    ANEMO_ENERGY_COST = 74
    GEO_ENERGY_COST = 75
    CRYO_ENERGY_COST = 76

    # others
    COOLDOWN_REDUCTION = 80
    SHIELD_STRENGTH = 81

    # current energy
    CURRENT_PYRO_ENERGY = 1000
    CURRENT_ELECTRO_ENERGY = 1001
    CURRENT_HYDRO_ENERGY = 1002
    CURRENT_DENDRO_ENERGY = 1003
    CURRENT_ANEMO_ENERGY = 1004
    CURRENT_GEO_ENERGY = 1005
    CURRENT_CRYO_ENERGY = 1006

    # hp
    CURRENT_HP = 1010
    MAX_HP = 2000

    # not sure what these are
    ATK_ = 2001
    DEF_ = 2002
    SPD_ = 2003

    # elemental reaction
    ELEMENTAL_REACTION_CRIT_RATE = 3025
    ELEMENTAL_REACCTION_CRIT_DMG = 3026
    ELEMENTAL_REACTION_OVERLOAD_CRIT_RATE = 3027
    ELEMENTAL_REACTION_OVERLOAD_CRIT_DMG = 3028
    ELEMENTAL_REACTION_SWIRL_CRIT_RATE = 3029
    ELEMENTAL_REACTION_SWIRL_CRIT_DMG = 3030
    ELEMENTAL_REACTION_ELECTRO_CHARGED_CRIT_RATE = 3031
    ELEMENTAL_REACTION_ELECTRO_CHARGED_CRIT_DMG = 3032
    ELEMENTAL_REACTION_SUPERCONDUCT_CRIT_RATE = 3033
    ELEMENTAL_REACTION_SUPERCONDUCT_CRIT_DMG = 3034
    ELEMENTAL_REACTION_BURN_CRIT_RATE = 3035
    ELEMENTAL_REACTION_BURN_CRIT_DMG = 3036
    ELEMENTAL_REACTION_FROZEN_SHATTERED_CRIT_RATE = 3037
    ELEMENTAL_REACTION_FROZEN_SHATTERED_CRIT_DMG = 3038
    ELEMENTAL_REACTION_BLOOM_CRIT_RATE = 3039
    ELEMENTAL_REACTION_BLOOM_CRIT_DMG = 3040
    ELEMENTAL_REACTION_BURGEON_CRIT_RATE = 3041
    ELEMENTAL_REACTION_BURGEON_CRIT_DMG = 3042
    ELEMENTAL_REACTION_HYPERBLOOM_CRIT_RATE = 3043
    ELEMENTAL_REACTION_HYPERBLOOM_CRIT_DMG = 3044
    BASE_ELEMENTAL_REACTION_CRIT_RATE = 3045
    BASE_ELEMENTAL_REACTION_CRIT_DMG = 3046
