name: Type Check

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/pyright.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/pyright.yml'

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install Project
        run: uv sync --frozen --no-dev --group type-check --extra redis --extra sqlite

      - name: Run Pyright
        run: uv run pyright enka/ --outputjson
